### ISSUE TITLE
Could you update?

### ISSUE THREAD

**Issue by Rishan0120** [rtao258/openev-downloader#1]
Would you be able to update this so that it works with the new high school wiki and open evidence project 

hswiki - https://opencaselist.com/hspolicy22
openev - https://opencaselist.com/openev
it also needs a tabroom password and email to log into the site first

**Comment by rtao258** [comment]
@Rishan0120 Sorry for the late reply. The presence of the login complicates matters. I think it's doable with `mechanize` or Selenium, but I don't know how. I am not a great programmer and threw together the original script as a one-off tool. I can look into updating it eventually. I tend to be busy with other things, so I may not get to it.
